[[plugins]] repo = 'yaasita/ore_markdown'
hook_post_update = '''
let cmd = 'bundle install --gemfile=~/.cache/dein/repos/github.com/yaasita/ore_markdown/bin/Gemfile'
let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'sunaku/vim-ruby-minitest'

[[plugins]]
repo = 'fatih/vim-go'
